name: window watcher server

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
    push:
        branches: [ "main" ]

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: docker.maerkl.net
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PWD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Inject Service Account
              run: 'echo "$FIREBASE_SERVICE_ACCOUNT" > /app/config/service-account.json'
              shell: bash
              env:
                  FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v3
              with:
                file: ./Dockerfile
                push: true # Will only build if this is not here
                tags: |
                    docker.maerkl.net/window-watcher-server:latest